export const PRODUCTS = [
  {
    id: 'original',
    name: 'Original',
    price: 45,
    size: '4 oz',
    image: '/images/veil-original-scent.png',
    category: 'fragrance',
    badge: 'Bestseller',
    tagline: 'jasmine · hinoki · vanilla',
    description: 'The signature VEIL scent — a featherlight perfume powder that melts into skin and lingers all day, noticed only by those who lean in close.',
    longDescription: 'The powder that started it all. A soft, warm composition of jasmine, hinoki and vanilla, pressed into the skin rather than projected into the air. It wears close and lasts all day with a soft-focus finish that draws people in.',
    notes: {
      top: 'Bergamot · Citrus zest',
      middle: 'Jasmine · Soft floral petals',
      base: 'Hinoki · Santal · Warm vanilla',
    },
    wear: 'The wear of a full perfume bottle',
    finish: 'Melts in — holds all day with a soft-focus finish',
  },
  {
    id: 'citron',
    name: 'Citron Lumineaux',
    price: 45,
    size: '4 oz',
    image: '/images/veil-citron-two.png',
    category: 'fragrance',
    badge: '',
    tagline: 'bergamot · neroli · cedar',
    description: 'A luminous citrus veil — crisp and close to the skin, a bright counterpart to the Original.',
    longDescription: 'Citron Lumineaux captures sunlit afternoons: crisp bergamot and neroli settling into a soft base of cedar and white woods. A gentle citrus veil that lasts all day without projecting — fragrance as an intimate secret.',
    notes: {
      top: 'Bergamot · Grapefruit',
      middle: 'Neroli · Petitgrain · White florals',
      base: 'Cedar · White woods',
    },
    wear: 'The wear of a full perfume bottle',
    finish: 'Soft-focus, close-to-skin scent',
  },
  {
    id: 'ritual-set',
    name: 'The Ritual Set',
    price: 58,
    size: 'powder + puff',
    image: '/images/veil-original-scent-2.png',
    category: 'set',
    badge: 'Gift',
    tagline: 'powder + grand puff',
    description: 'The Original powder paired with our oversized Grand Puff — the complete ritual, and $7 saved.',
    longDescription: 'Everything the ritual needs: a full jar of the Original Scent and the extra-large Grand Puff for soft, even application. Presented in a matte tin with a hand-drawn label — beautiful enough to gift unwrapped.',
    notes: {
      top: 'Bergamot · Citrus zest',
      middle: 'Jasmine · Soft floral petals',
      base: 'Hinoki · Santal · Warm vanilla',
    },
    wear: 'The wear of a full perfume bottle',
    finish: 'Melts in — holds all day with a soft-focus finish',
  },
  {
    id: 'grand-jar',
    name: 'Grand Jar',
    price: 64,
    size: '8 oz',
    image: '/images/veil-grand-jar.png',
    category: 'fragrance',
    badge: '',
    tagline: 'original · extended wear',
    description: 'The Original Scent in our larger Grand Jar — more wear, the same intimate finish.',
    longDescription: 'For those who live in the Original Scent, the Grand Jar offers extended wear with the same meticulous formula. A larger format means more applications, more days of soft, intimate fragrance.',
    notes: {
      top: 'Bergamot · Citrus zest',
      middle: 'Jasmine · Soft floral petals',
      base: 'Hinoki · Santal · Warm vanilla',
    },
    wear: 'Multiple wears — the extended-wear option',
    finish: 'Melts in — holds all day with a soft-focus finish',
  },
  {
    id: 'puff',
    name: 'The Grand Puff',
    price: 10,
    size: 'oversized',
    image: '',
    category: 'accessory',
    badge: '',
    tagline: 'soft · refillable ritual',
    description: 'Our signature oversized applicator puff — soft, durable, and made for the ritual.',
    longDescription: 'Hand-selected for softness and durability, the Grand Puff makes applying VEIL a tactile ritual. The extra-large size ensures even distribution, and the gentle texture is kind to even sensitive skin.',
    notes: null,
    wear: 'Essential application tool',
    finish: 'Soft, durable, reusable',
  },
];

export const getProductById = (id) => PRODUCTS.find((p) => p.id === id);
export const getProductsByCategory = (category) => PRODUCTS.filter((p) => p.category === category);
export const getFeaturedProducts = () => PRODUCTS.filter((p) => ['original', 'citron', 'ritual-set'].includes(p.id));
