export const PRODUCTS = [
  {
    id: 'original',
    name: 'Original',
    price: 45,
    size: '4 oz',
    images: ['/images/veil-original-scent.png', '/images/veil-original-scent-2.png', '/images/veil-puff-model-white-robe.png'],
    category: 'fragrance',
    badge: 'Bestseller',
    tagline: 'jasmine · hinoki · vanilla',
    description: 'The signature VEIL scent — a featherlight perfume powder that melts into skin and lingers all day, noticed only by those who lean in close.',
    longDescription: 'The powder that started it all. A soft, warm composition of jasmine, hinoki and vanilla, pressed into the skin rather than projected into the air. It wears close and lasts all day with a soft-focus finish that draws people in.',
    notes: {
      top: 'Bergamot · Citrus zest',
      middle: 'Jasmine · Soft floral petals',
      base: 'Hinoki · Santal · Warm vanilla',
    },
    wear: 'The wear of a full perfume bottle',
    finish: 'Melts in — holds all day with a soft-focus finish',
  },
  {
    id: 'citron',
    name: 'Citron Lumineaux',
    price: 45,
    size: '4 oz',
    images: ['/images/citron-main.png', '/images/veil-citron-two.png', '/images/citron-scent.png', '/images/veil-puff-model-white-robe.png'],
    category: 'fragrance',
    badge: '',
    tagline: 'bergamot · neroli · cedar',
    description: 'A luminous citrus veil — crisp and close to the skin, a bright counterpart to the Original.',
    longDescription: 'Citron Lumineaux captures sunlit afternoons: crisp bergamot and neroli settling into a soft base of cedar and white woods. A gentle citrus veil that lasts all day without projecting — fragrance as an intimate secret.',
    notes: {
      top: 'Bergamot · Grapefruit',
      middle: 'Neroli · Petitgrain · White florals',
      base: 'Cedar · White woods',
    },
    wear: 'The wear of a full perfume bottle',
    finish: 'Soft-focus, close-to-skin scent',
  },
  {
    id: 'grand-jar',
    name: 'Grand Jar',
    price: 64,
    size: '8 oz',
    images: ['/images/veil-grand-jar.png', '/images/veil-grand-jar-2.png', '/images/veil-puff-model-white-robe.png'],
    category: 'fragrance',
    badge: '',
    tagline: 'original · extended wear',
    description: 'The Original Scent in our larger Grand Jar — more wear, the same intimate finish.',
    longDescription: 'For those who live in the Original Scent, the Grand Jar offers extended wear with the same meticulous formula. A larger format means more applications, more days of soft, intimate fragrance.',
    notes: {
      top: 'Bergamot · Citrus zest',
      middle: 'Jasmine · Soft floral petals',
      base: 'Hinoki · Santal · Warm vanilla',
    },
    wear: 'Multiple wears — the extended-wear option',
    finish: 'Melts in — holds all day with a soft-focus finish',
  },
  {
    id: 'violette',
    name: 'Violette Ambrée',
    price: 45,
    size: '4 oz',
    images: ['/images/violette-scent-1.png', '/images/veil-puff-model-white-robe.png'],
    category: 'fragrance',
    badge: 'New',
    tagline: 'pear · lily of the valley · amber',
    description: 'Notes of pear, plum, lily of the valley, violet, amber, and warm woods.',
    longDescription: 'Our newest composition: crisp pear and dark plum open into a bouquet of lily of the valley and violet, settling into warm amber and soft woods. Delicate and romantic — a quieter counterpart to the Original.',
    notes: {
      top: 'Pear · Plum',
      middle: 'Lily of the Valley · Violet',
      base: 'Amber · Warm Woods',
    },
    wear: 'The wear of a full perfume bottle',
    finish: 'Soft, romantic, close-to-skin',
  },
  {
    id: 'scent-trio',
    name: 'The Scent Trio',
    price: 115,
    size: '3 × 4 oz',
    images: ['/images/scent-sampler.png', '/images/veil-puff-model-white-robe.png'],
    category: 'set',
    badge: 'Save $20',
    tagline: 'original · citron · violette',
    description: 'All three signature scents, bundled and saved.',
    longDescription: 'Original, Citron Lumineaux, and Violette Ambrée — our three signature powders in one set, so you can wear whichever the day calls for.',
    notes: null,
    wear: 'The wear of three full perfume bottles',
    finish: 'A scent for every mood',
  },
  {
    id: 'puff',
    name: 'The Grand Puff',
    price: 10,
    size: 'oversized',
    images: ['/images/large-puff.png', '/images/veil-puff-model-white-robe.png'],
    category: 'accessory',
    badge: '',
    tagline: 'soft · refillable ritual',
    description: 'Our signature oversized applicator puff — soft, durable, and made for the ritual.',
    longDescription: 'Hand-selected for softness and durability, the Grand Puff makes applying VEIL a tactile ritual. The extra-large size ensures even distribution, and the gentle texture is kind to even sensitive skin.',
    notes: null,
    wear: 'Essential application tool',
    finish: 'Soft, durable, reusable',
  },
];

// A checkout-only free-gift offer — deliberately not part of PRODUCTS so it
// never shows up in the shop grid or search; it's only ever added via the
// timed offer on the checkout page.
export const TASSEL_GIFT = {
  id: 'tassel',
  name: 'Veil Scented Tassel',
  price: 15,
  size: 'one size',
  images: ['/images/veil-scented-tassel.png'],
  category: 'gift',
};

export const getProductById = (id) => PRODUCTS.find((p) => p.id === id);
export const getProductsByCategory = (category) => PRODUCTS.filter((p) => p.category === category);
export const getFeaturedProducts = () => PRODUCTS.filter((p) => ['original', 'citron', 'grand-jar', 'violette'].includes(p.id));
